// src/app/core/models/student.model.ts

export interface Address {
  id?: number;
  cep: string;
  street: string;
  number: string;
  complement?: string;
  neighborhood: string;
  city: string;
  state: string;
}

export interface User {
  id?: number;
  keycloakUserId?: string;
  name: string;
  email: string;
  cpf: string;
  birthDate: string;
  phone: string;
  address?: Address;
  profileId: number; // Changed from profile string to profileId (1=admin, 2=professor, 3=student)
  active: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface Student {
  id?: number;
  userId?: number;
  user: User;
  programIds?: number[];
  registrationNumber?: string; // READONLY - generated by backend
  status?: StudentStatus; // ENUM - readonly on creation form
  specialNeeds?: string;
  medicalInfo?: string;
  // Deprecated fields removed
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * CreateStudentRequest - Used to create a student
 * ❌ NO registration_number (backend generates automatically)
 * ❌ NO status (backend sets to 'active' by default)
 */
export interface CreateStudentRequest {
  user: {
    name: string;
    email: string;
    cpf: string;
    birthDate: string;
    phone: string;
    address: Address;
    profileId: number; // 3 = student
    active: boolean;
    password: string;
  };
  programIds?: number[];
  // ❌ registrationNumber removed - auto-generated by backend
  // ❌ status removed - defaults to 'active'
  specialNeeds?: string;
  medicalInfo?: string;
  notes?: string;
}

/**
 * UpdateStudentRequest - Used to update a student
 * ✅ CAN change status
 */
export interface UpdateStudentRequest {
  user?: Partial<Omit<User, "id" | "keycloakUserId" | "profileId">>;
  programIds?: number[];
  // ❌ registrationNumber cannot be updated
  status?: StudentStatus; // ✅ Allowed in UPDATE
  specialNeeds?: string;
  medicalInfo?: string;
  notes?: string;
}

export type StudentStatus = "active" | "inactive" | "suspended";

export const STUDENT_STATUS_LABELS: Record<StudentStatus, string> = {
  active: "Ativo",
  inactive: "Inativo",
  suspended: "Suspenso",
};

// Guardian interface (for future use)
export interface Guardian {
  id: number;
  studentId: number;
  name: string;
  email?: string;
  cpf?: string;
  relationship: string;
  phones: {
    number: string;
    type: "personal" | "work" | "home";
  }[];
  permissions: {
    pickupStudent: boolean;
    receiveNotifications: boolean;
    authorizeActivities: boolean;
  };
}
